<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.octopus8.jobs/xml/schema/CRM/Jobs/02_SscApplication.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:50746781919bdee064315694e1b27dd9)
 */
use CRM_Jobs_ExtensionUtil as E;

/**
 * Database access object for the SscApplication entity.
 */
class CRM_Jobs_DAO_SscApplication extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_o8_job_application';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SSC Application ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * @var int
   */
  public $status_id;

  /**
   * Is the Application active or withdrawn?
   *
   * @var bool
   */
  public $is_active;

  /**
   * FK to SSC Job
   *
   * @var int
   */
  public $o8_job_id;

  /**
   * Date and time the application was created
   *
   * @var timestamp
   */
  public $created_date;

  /**
   * FK to civicrm_contact, who created this application
   *
   * @var int
   */
  public $created_id;

  /**
   * Date and time the application was modified
   *
   * @var timestamp
   */
  public $modified_date;

  /**
   * FK to civicrm_contact, who modified this application
   *
   * @var int
   */
  public $modified_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_o8_job_application';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Ssc Applications') : E::ts('Ssc Application');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'o8_job_id', 'civicrm_o8_job', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'created_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'modified_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique SSC Application ID'),
          'required' => TRUE,
          'where' => 'civicrm_o8_job_application.id',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'where' => 'civicrm_o8_job_application.contact_id',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Application for Job Status'),
          'import' => TRUE,
          'where' => 'civicrm_o8_job_application.status_id',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'o8_application_status',
            'optionEditPath' => 'civicrm/admin/options/o8_application_status',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Application Active?'),
          'description' => E::ts('Is the Application active or withdrawn?'),
          'required' => TRUE,
          'where' => 'civicrm_o8_job_application.is_active',
          'default' => '1',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'add' => NULL,
        ],
        'o8_job_id' => [
          'name' => 'o8_job_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to SSC Job'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_job_application.o8_job_id',
          'export' => TRUE,
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'FKClassName' => 'CRM_Jobs_DAO_SscJob',
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Application Created Date'),
          'description' => E::ts('Date and time the application was created'),
          'required' => TRUE,
          'where' => 'civicrm_o8_job_application.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'created_id' => [
          'name' => 'created_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Created By Contact ID'),
          'description' => E::ts('FK to civicrm_contact, who created this application'),
          'required' => FALSE,
          'where' => 'civicrm_o8_job_application.created_id',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'label' => E::ts("Created By"),
          ],
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Application Created Date'),
          'description' => E::ts('Date and time the application was modified'),
          'required' => FALSE,
          'where' => 'civicrm_o8_job_application.modified_date',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'modified_id' => [
          'name' => 'modified_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Modified By Contact ID'),
          'description' => E::ts('FK to civicrm_contact, who modified this application'),
          'where' => 'civicrm_o8_job_application.modified_id',
          'table_name' => 'civicrm_o8_job_application',
          'entity' => 'SscApplication',
          'bao' => 'CRM_Jobs_DAO_SscApplication',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'label' => E::ts("Created By"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'o8_job_application', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'o8_job_application', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
