-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_ssc_job`;
DROP TABLE IF EXISTS `civicrm_ssc_application`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_ssc_job
-- *
-- * Social Services Connect Job Proposals
-- *
-- *******************************************************/
CREATE TABLE `civicrm_ssc_job` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SSC Job ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `title` varchar(255) NULL,
  `description` longtext NULL,
  `role_id` int DEFAULT 1,
  `location_id` int DEFAULT 1,
  `status_id` int DEFAULT 1,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the job was created',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this application',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_ssc_job_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_ssc_job_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;


-- /*******************************************************
-- *
-- * civicrm_ssc_application
-- *
-- * Social Services Connect Job Application
-- *
-- *******************************************************/
CREATE TABLE `civicrm_ssc_application` (
                                           `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SSC Application ID',
                                           `contact_id` int unsigned COMMENT 'FK to Contact',
                                           `status_id` int DEFAULT 1,
                                           `ssc_job_id` int unsigned NOT NULL COMMENT 'FK to SSC Job',
                                           `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the application was created',
                                           `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this application',
                                           PRIMARY KEY (`id`),
                                           CONSTRAINT FK_civicrm_ssc_application_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
                                           CONSTRAINT FK_civicrm_ssc_application_ssc_job_id FOREIGN KEY (`ssc_job_id`) REFERENCES `civicrm_ssc_job`(`id`) ON DELETE CASCADE,
                                           CONSTRAINT FK_civicrm_ssc_application_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
    ENGINE=InnoDB;

DELETE FROM civicrm_option_value WHERE `description` LIKE "CRM_Job%";