-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_job`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_job
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_job` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Job ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `title` varchar(255) NULL,
  `job_role_id` int DEFAULT 1,
  `job_location_id` int DEFAULT 1,
  `job_status_id` int DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_job_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
